/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/nokia.glb --transform --simplify 
Files: public/nokia.glb [321.25KB] > /Users/matt/Desktop/code/what-i-love/29-nokia-phone/nokia-transformed.glb [41.83KB] (87%)
Author: KI NG (https://sketchfab.com/dadybandit)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-nokia-phone-low-poly-a022864ae7b642a39469652c3eda2b9a
Title: old nokia phone low poly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/nokia-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_back_0.geometry} material={materials.back} position={[-89.008, -25.512, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[44.74, 21.863, 44.74]} />
      <mesh geometry={nodes.Cube_side_0.geometry} material={materials.side} position={[-89.008, -25.512, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[44.74, 21.863, 44.74]} />
      <mesh geometry={nodes.Cube_screen_0.geometry} material={materials.screen} position={[-89.008, -25.512, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[44.74, 21.863, 44.74]} />
    </group>
  )
}

useGLTF.preload('/nokia-transformed.glb')
