/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bar.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import FakeGlowMaterial from './FakeGlowMaterial'


export default function Bar(props) {
  const { nodes, materials } = useGLTF('/bar.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BezierCurve.geometry} rotation={[0, 0, -Math.PI * 0.5]}>
        <FakeGlowMaterial
          glowColor='#d4361e'
          glowSharpness={10}
          falloff={1}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/bar.glb')
