/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/monalisa.glb --transform --simplify 
Files: public/monalisa.glb [659.97KB] > /Users/matt/Desktop/code/what-i-love/28-monalisa/monalisa-transformed.glb [122KB] (82%)
Author: Milan (https://sketchfab.com/milanfonken)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/monalisa-fa55dc4f8b7f4ac398f3aee7b5e047bc
Title: Monalisa
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/monalisa-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material_27} position={[-8.494, 51.339, -15.709]} rotation={[0, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/monalisa-transformed.glb')
