/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 what-i-love/21-world/public/portfolio/computer.glb --transform --simplify 
Files: what-i-love/21-world/public/portfolio/computer.glb [27.58KB] > /Users/matt/Desktop/code/computer-transformed.glb [18.25KB] (34%)
*/

import * as THREE from 'three'
import { React, useRef } from 'react'
import { useGLTF, Merged, RenderTexture, PerspectiveCamera, Text } from '@react-three/drei'
import { useFrame } from "@react-three/fiber"
import { EffectComposer, Bloom, Select, ToneMapping } from '@react-three/postprocessing'
import { ToneMappingMode } from 'postprocessing'
import FloatingText from './GlowingText'


export function Computer(props) {
  const { nodes, materials } = useGLTF('./portfolio/computer.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-5, 0.4, -0.5]} scale={[6, 4, 4]}>
        <mesh geometry={nodes.Object_3002.geometry} material={materials.texture3} />
        <mesh geometry={nodes.Object_3002_1.geometry} material={materials.texture2} />
        <mesh geometry={nodes.Object_3002_2.geometry} material={materials.texture4} />
        <mesh geometry={nodes.Object_3002_3.geometry} material={materials.texture6} />
        <mesh geometry={nodes.Object_3002_4.geometry} material={materials.texture5} />
        <mesh geometry={nodes.Object_3002_5.geometry} material={materials.texture} />
        <mesh geometry={nodes.Object_3002_6.geometry} material={materials.texture7} />
        <mesh geometry={nodes.Object_3002_7.geometry} material={materials.texture8} />
        <mesh geometry={nodes.Object_3002_8.geometry} material={materials.texture9} />
        <mesh geometry={nodes.Object_3002_9.geometry} material={materials.texture10} />
      </group>
      <mesh
        geometry={new THREE.PlaneGeometry(0.69, 0.38)}
        position={[-5.34, 1.4, 0.26]}
        scale={2.05}

      >
        <meshStandardMaterial toneMapped={false} emissive="#35c193" emissiveIntensity={2}>
          <RenderTexture
            attach="map"
            anisotropy={16}
          >
            <color attach="background" args={['#35c19f']} />
            <PerspectiveCamera makeDefault manual aspect={1 / 1} position={[0, 0, 18]} />
            <FloatingText />
          </RenderTexture>
        </meshStandardMaterial>
      </mesh>

      <EffectComposer disableNormalPass>
        <ToneMapping mode={ToneMappingMode.ACES_FILMIC} />
        <Bloom
          luminanceThreshold={0.8}
          intensity={4}
          mipmapBlur
        />
      </EffectComposer>
    </group >
  )
}

useGLTF.preload('./portfolio/computer.glb')

